### ISSUE TITLE
Link tag color changes after app restart

### ISSUE THREAD

**Issue by Elbullazul** [rainloreley/shlink-manager#1]
I noticed that the tag color always changes when restarting.

Ex. when first opening the app, the tag "private" has a green color, but after restarting the app, the tag's color is now blue.

Somewhat related, could the color assigned to the tag be the same as the one selected from shlink-web?

**Comment by rainloreley** [comment]
That behavior is intentional (for now), the app just uses a random color every time the list reloads. There's a way to tie a tag to a specific color, I just didn't get around to add it yet...

> could the color assigned to the tag be the same as the one selected from shlink-web?

Sadly no, the [Shlink API](https://api-spec.shlink.io/#/Tags) only returns the tag name. The color of a tag is not handled by Shlink at all, it's stored in the [browsers' local storage](https://github.com/shlinkio/shlink-web-client/blob/63dd386604904d6b2507d15ec1db09bfe5748019/src/utils/services/TagColorsStorage.ts) by shlink-web. There's no way for the app to access that (and based on this, the colors probably shouldn't even be the same if you use a different device to access shlink-web)

**Comment by rainloreley** [comment]
fixed in d00ba4b4e926dbe5673975a6ed14143c0d3dfc70
