### ISSUE TITLE
[Bug] type 'Null' is not a subtype of type 'Map<String, dynamic>'

### ISSUE THREAD

**Issue by Daenges** [rainloreley/shlink-manager#2]
In the last few days I got this error message by opening the Home or Short Links tab.

Works fine in browser.

![Screenshot_20240319-152021.png](https://github.com/rainloreley/shlink-manager/assets/57369924/30915a26-3cd8-45df-b4ce-39a1bae5fd97)

**Comment by rainloreley** [comment]
Hi, thanks for reporting the issue! As far as I can tell, this bug is caused by the new dynamic redirects feature in [Shlink v4.0.0](https://github.com/shlinkio/shlink/releases/tag/v4.0.0), more specifically the restructuring of device specific redirects (https://github.com/shlinkio/shlink/issues/1914). Previously they had their own entry in the data, but they seemingly removed that and moved it to dynamic redirects. This means the app currently can't detect these device specific URLs and fails.

I'll try to fix the issue in the next few days and push an update. Sadly they changed the spec of the v3 API (which Shlink Manager uses), instead of publishing a new API version (which I kinda expect when you change the response data), so the app will be broken until I can fix this :/

**Comment by arpanghosh8453** [comment]
Sorry to hear this. Do you have any update on this yet?

Thanks again for all the hard work ❤️

**Comment by rainloreley** [comment]
I temporarily fixed the issue by removing device specific URLs for now, the update should be available soon (i'll upload it in a few minutes). Sorry for the delay, I've been quite busy the last few weeks

**Comment by arpanghosh8453** [comment]
No worries. Thank you for the hard work! Appreciate it.
